apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-31bd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-omia-tenant/rhtap-demo-app/hacbs-test-project-31bd@sha256:9190de4de920f33df1ecc8655739f450003ef57899c99a3e13d8a1eba63dd147
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
