apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-31bd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-31bd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-31bd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-31bd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-31bd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-omia-tenant/rhtap-demo-app/hacbs-test-project-31bd@sha256:9190de4de920f33df1ecc8655739f450003ef57899c99a3e13d8a1eba63dd147
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
